title: José Miguel Horcas Aguilera
author: José Miguel Horcas
email: horcas@uma.es
description: Personal website
baseurl: "" # Empty Leave it empty if it's for a github.io domain
url: "https://jmhorcas.github.io"

# Markdown configuration
markdown: kramdown

collections_dir: collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/
  awards:
    output: true
    permalink: /awards/:path/
  community_service:
    output: true
    permalink: /community-service/:path/
  media:
    output: true
    permalink: /media/:path/
  software:
    output: true
    permalink: /software/:path/
  supervision:
    output: true
    permalink: /supervision/:path/
  education:
    output: true
    permalink: /education/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "publications" 
    values:
      layout: "default"

scholar:
  citations: 849
  h_index: 17
  i10_index: 30